### PR TITLE
Add implementation for stream endpoints

### PR DESCRIPTION
**Pull request by marekfilip**

### CODE REVIEW

**Comment by agilob** [comment]
I think the functionality should also offer stream for logged in users. When I browse "stream" I don't want to see entries with my blocked tags. This can go to another PR if you wish.

**Comment by marekfilip** [comment]
Of course, it would be really nice feature but I can't find way, how to do that. Just tried adding a `userkey` to the request but it was ignored. I couldn't find an endpoint that would deliver user blocked tags for late filtering as well. Got any clue?

**Comment by agilob** [comment]
In case of link from main page I just build url `appkey/%s/userkey/%s/page/%`. I noticed that in `profile/block/user` order of parameters is important:
`/profile/block/%s/userkey/%s/appkey/%s` - works
`/profile/block/%s/appkey/%s/userkey/%s` - doesn't work, request is ignored.

**Comment by marekfilip** [comment]
Ok, if everything's alright, merge `implement_stream`. I will run an issue for getting stream without blocked tags, investigate and implement. Ok?

**Comment by agilob** [comment]
commit hash 13221dd

**Pull request merged**
